# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes', models.IntegerField()),
                ('no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='news_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('heading', models.TextField()),
                ('passage', models.TextField()),
                ('author', models.CharField(default='rowling', max_length=200)),
                ('website', models.CharField(default='rowling', max_length=200)),
                ('image_link', models.CharField(default='rowling', max_length=200)),
            ],
        ),
    ]
