# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_no', models.IntegerField(default=0)),
            ],
        ),
    ]
